#!/bin/sh
which dirname >/dev/null
# does dirname exit?
if [ $? = 0 ] ; then
  cwd=`dirname $0`
  if [ x$cwd = x. ]; then
     cwd=`pwd`
  fi
  if [ x$cwd = x/usr/sbin ] ; then
     echo "bconsole not properly installed."
     exit 1
  fi
fi
if [ x/usr/sbin = x/etc/bareos ]; then
   echo "bconsole not properly installed."
   exit 1
fi
if [ x/usr/sbin = x/etc ]; then
   echo "bconsole not properly installed."
   exit 1
fi
if [ $# = 1 ] ; then
   echo "doing bconsole $1.conf"
   /usr/sbin/bconsole -c $1.conf
else
   /usr/sbin/bconsole -c /etc/bareos/bconsole.conf
fi
